name: CI

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
      - name: cache dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: |
          yarn install --frozen-lockfile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check

    unit-tests:
      # Runs all tests and post failed checks to PR
      name: Unit tests
      runs-on: ubuntu-latest
      needs: install
      steps:
        - uses: actions/checkout@v2.3.4
        - uses: actions/cache@v2
          with:
            path: '**/node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
        - uses: mattallty/jest-github-action@v1
          # This action has a bug running tests only on changed files
          env:
            GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
          with:
            test-command: "yarn test --ci --coverage --maxWorkers=2 --collectCoverageFrom='src/**/*js' --collectCoverageFrom='!/node_modules/' --collectCoverageFrom='!src/**/*.stories.js' --coverageReporters lcov --coverageReporters json-summary"
            coverage-comment: false
