name: CI

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2.3.4
      - name: cache dependencies
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: |
          yarn install --frozen-lockfile
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: install
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-check

  unit-tests:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Check out source code
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
      - name: use cache
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - name: Run unit tests
        run: yarn run test-unit --onlyChanged
