name: Linting
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.4.1
        with:
          node-version: '14.x'
      - name: Update npm
        run: npm install -g npm@7.1.1
      - name: Install modules
        run: npm install --no-optional
      - name: Run ESLint
        run: yarn lint
